version: '3'

services:
  mongo:
    image: mongo:4.2.3
    volumes:
    - ./data/db:/data/db
    ports:
    - "27017:27017"
    restart: always
  redis:
    image: redis:3.2.8-alpine
    volumes:
    - ./data/redis:/data
    ports:
    - "6379:6379"
    restart: always
